name: Reproduce Issue

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Install dependencies
        run: |
          npm install --global @salesforce/cli
          sf --version
          sf plugins --core
      - name: Authenticate DevHub and create scratch org
        env:
          SFDX_AUTH_URL_DEVHUB: ${{ secrets.SFDX_AUTH_URL_DEVHUB }}
        run: |
          echo "${SFDX_AUTH_URL_DEVHUB}" | sf org login sfdx-url --set-default-dev-hub --sfdx-url-stdin
          sf org create scratch -f config/project-scratch-def.json -d -a mre-incorrect-source-member-type-quickactiondefinition
          sf project deploy start
      - name: Reproduce issue
        run: |
          # delete Global Action in the Scratch Org
          npm install @salesforce/core
          npx -c ./scripts/delete-global-action.mjs
          sf project retrieve preview
      - name: Delete scratch org
        if: always()
        run: |
          sf org delete scratch -p
